name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0

      - name: Install Dependencies
        run: go mod tidy

      - name: Install Prisma Client Go
        run: go install github.com/steebchen/prisma-client-go@latest

      - name: Generate Prisma Client
        run: go run github.com/steebchen/prisma-client-go generate

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
